language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t deepaksivaramanpandi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true deepaksivaramanpandi/docker-react npm run test -- --coverage
